version: "3"
services: 
    app:
        build: .
        command: ["sh", "run.sh"]
        environment: 
            DISPLAY: "unix$DISPLAY"
        volumes: 
            - /tmp/.X11-unix:/tmp/.X11-unix
    db:
        image: mysql:5
        command: --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ROOT_PASSWORD: 123
          MYSQL_DATABASE: stockfinal
        ports: 
            - 3306:3306
